Fix compiltion under Java 7
Error message is:

   ModulePresenterImpl.java:134: error: local variable paramValues is accessed
   from within inner class; needs to be declared final

   List<Object> filledReturnValues = invoker.invoke(module, paramValues);
                                                            ^

Found via Travis.

Signed-off-by: Uli Schlachter <uli.schlachter@informatik.uni-oldenburg.de>